services:
    app:
        container_name: emr
        build:
            context: .
        ports:
            - "80:80"
            - "8000:8000"
            - "443:443"
            - "9000:9000"
        env_file: .env
        command: [ "/bin/sh", "-c", "php artisan config:clear; php artisan serve --host 0.0.0.0" ]
    # postgres:
    #     image: postgres:17
    #     ports:
    #         - 5432:5432
    #     environment:
    #         - POSTGRES_PASSWORD=${DB_PASSWORD}
    #         - POSTGRES_DEFAULT_USER=${DB_USER}
    # redis:
    #     container_name: redis
    #     image: redis:8.4
    #     ports:
    #         - 6379:6379
    #     volumes:
    #         - redis

volumes:
    db:
    redis:
